# Generated by Django 4.2.7 on 2024-02-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
