# Generated by Django 4.2.6 on 2024-02-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad1', '0002_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
