# Generated by Django 5.0.2 on 2024-04-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad1', '0003_remove_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
