# Generated by Django 5.0.2 on 2024-03-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNombre', models.CharField(max_length=50)),
                ('carDuracion', models.CharField(max_length=50)),
                ('carMaterias', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estNombre', models.CharField(max_length=30)),
                ('estApellido', models.CharField(max_length=50)),
                ('estEmail', models.EmailField(max_length=254)),
                ('estTelefono', models.IntegerField(max_length=10)),
                ('estFechaNacimiento', models.DateField()),
                ('estFoto', models.ImageField(upload_to='')),
                ('estFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('estFechaActualizacion', models.DateTimeField(auto_now=True)),
                ('estCarrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matNombre', models.CharField(max_length=50)),
                ('matDescripcion', models.TextField()),
                ('matCreditos', models.IntegerField(max_length=5)),
                ('matFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('matFechaActualizacion', models.DateTimeField(auto_now=True)),
                ('matCarrera', models.CharField(max_length=50)),
                ('matProfesores', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profNombre', models.CharField(max_length=30)),
                ('profApellido', models.CharField(max_length=50)),
                ('profEmail', models.EmailField(max_length=254)),
                ('profTelefono', models.IntegerField(max_length=10)),
                ('profFechaNacimiento', models.DateField()),
                ('profFoto', models.ImageField(upload_to='')),
                ('profFechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('profFechaActualizacion', models.DateTimeField(auto_now=True)),
                ('profCMaterias', models.CharField(max_length=50)),
            ],
        ),
    ]
