# Generated by Django 5.0.2 on 2024-03-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCrud', '0002_alter_carrera_options_alter_estudiante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estFoto',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profFoto',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
