# Generated by Django 4.2.6 on 2024-04-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCrud', '0004_alter_carrera_carduracion_alter_carrera_carmaterias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estTelefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='matCreditos',
            field=models.IntegerField(verbose_name='Creditos'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profTelefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
