# Generated by Django 5.0.2 on 2024-04-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCrud', '0005_alter_estudiante_esttelefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='profCMaterias',
        ),
        migrations.AddField(
            model_name='profesor',
            name='profMaterias',
            field=models.ManyToManyField(to='GestionCrud.materia', verbose_name='Materias'),
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='carMaterias',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCrud.carrera', verbose_name='Carrera'),
        ),
        migrations.RemoveField(
            model_name='materia',
            name='matCarrera',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='matProfesores',
        ),
        migrations.AddField(
            model_name='carrera',
            name='carMaterias',
            field=models.ManyToManyField(to='GestionCrud.materia', verbose_name='Materias'),
        ),
        migrations.AddField(
            model_name='materia',
            name='matCarrera',
            field=models.ManyToManyField(to='GestionCrud.carrera', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='materia',
            name='matProfesores',
            field=models.ManyToManyField(to='GestionCrud.profesor', verbose_name='Materias'),
        ),
    ]
