# Generated by Django 5.0.2 on 2024-04-04 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCrud', '0006_remove_profesor_profcmaterias_profesor_profmaterias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='matProfesores',
        ),
        migrations.AddField(
            model_name='materia',
            name='matProfesores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionCrud.profesor', verbose_name='Profesor'),
            preserve_default=False,
        ),
    ]
