# Generated by Django 4.2.6 on 2024-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCrud', '0007_remove_materia_matprofesores_materia_matprofesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='carMaterias',
            field=models.ManyToManyField(blank=True, null=True, to='GestionCrud.materia', verbose_name='Materias'),
        ),
    ]
