# Generated by Django 4.2.6 on 2024-04-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCrud', '0009_alter_carrera_carmaterias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='matProfesores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCrud.profesor', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profMaterias',
            field=models.ManyToManyField(blank=True, to='GestionCrud.materia', verbose_name='Materias'),
        ),
    ]
