# Generated by Django 4.2.6 on 2024-04-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCrud', '0010_alter_materia_matprofesores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='carMaterias',
            field=models.ManyToManyField(to='GestionCrud.materia', verbose_name='Materias'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estCarrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionCrud.carrera', verbose_name='Carrera'),
        ),
    ]
