# Generated by Django 5.0.2 on 2024-04-10 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCrud', '0011_alter_carrera_carmaterias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estCarrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCrud.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profFoto',
            field=models.ImageField(upload_to='profFotos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='profMaterias',
            field=models.ManyToManyField(to='GestionCrud.materia', verbose_name='Materias'),
        ),
    ]
